name: "todoApp"


version: 1.0.0+1


environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4 
  sqflite: ^2.0.3
  intl: ^0.17.0
  conditional_builder_null_safety: ^0.0.6

flutter:
  uses-material-design: true
  